language: node_js
node_js: 
    - node
cache:
  directories:
    - "node_modules"
# env: 
#   - NODE_ENV=production
install: 
  - npm install
script:
  - npm run build
  # - npm run test
# before_deploy: 
#   - "echo 'deploying'"
deploy:
  provider: azure_web_apps
  site: bookshelfpress.azurewebsites.net
  slot: production